# _config.yml
title: Chelsea's Portfolio
description: Her designs
baseurl: "" # keeping it empty for custom domain "/chelsea-portfolio"
url: "https://vicramon.github.io" # the base hostname & protocol for your site
